apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: m001-catalog-info
  description: Ejie catalogo info
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: nttdata
  lifecycle: experimental
  domain: cloud-apps
